"""nutrition match fields to per-100g

Revision ID: 00485806a4da
Revises: 8bd93416de90
Create Date: 2026-08-03 10:45:00.802612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00485806a4da'
down_revision: Union[str, None] = '8bd93416de90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Old values meant "portion-scaled calories" (LLM judgment call); new columns
    # mean "per 100g" (mostly raw USDA, or LLM only when no USDA match). These are
    # not the same number under a different name — existing rows can't be migrated
    # in place, so wipe and let app/jobs/enrich_items.py regenerate them.
    op.execute("TRUNCATE TABLE nutrition_matches")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_matches', sa.Column('calories_per_100g', sa.Float(), nullable=False))
    op.add_column('nutrition_matches', sa.Column('protein_g_per_100g', sa.Float(), nullable=False))
    op.add_column('nutrition_matches', sa.Column('carbs_g_per_100g', sa.Float(), nullable=False))
    op.add_column('nutrition_matches', sa.Column('fat_g_per_100g', sa.Float(), nullable=False))
    op.drop_column('nutrition_matches', 'calories')
    op.drop_column('nutrition_matches', 'protein_g')
    op.drop_column('nutrition_matches', 'fat_g')
    op.drop_column('nutrition_matches', 'carbs_g')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_matches', sa.Column('carbs_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('nutrition_matches', sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('nutrition_matches', sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('nutrition_matches', sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('nutrition_matches', 'fat_g_per_100g')
    op.drop_column('nutrition_matches', 'carbs_g_per_100g')
    op.drop_column('nutrition_matches', 'protein_g_per_100g')
    op.drop_column('nutrition_matches', 'calories_per_100g')
    # ### end Alembic commands ###
