"""add meals_per_day to user_preferences

Revision ID: 30bd5b7377ec
Revises: 00485806a4da
Create Date: 2026-08-03 11:04:12.242730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bd5b7377ec'
down_revision: Union[str, None] = '00485806a4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('meals_per_day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'meals_per_day')
    # ### end Alembic commands ###
