"""initial schema

Revision ID: 8bd93416de90
Revises: 
Create Date: 2026-08-02 11:18:16.794676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd93416de90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('diet_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('likely_allergens', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_tags_item_name'), 'diet_tags', ['item_name'], unique=True)
    op.create_table('eateries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cornell_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('eatery_type', sa.String(), nullable=False),
    sa.Column('campus_area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cornell_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('nutrition_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('usda', 'llm_estimate', name='nutritionsource'), nullable=False),
    sa.Column('usda_fdc_id', sa.String(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_matches_item_name'), 'nutrition_matches', ['item_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('menu_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eatery_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_period', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eatery_id'], ['eateries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eatery_id', 'date', 'meal_period')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calorie_goal', sa.Integer(), nullable=False),
    sa.Column('protein_goal_g', sa.Integer(), nullable=False),
    sa.Column('carb_goal_g', sa.Integer(), nullable=False),
    sa.Column('fat_goal_g', sa.Integer(), nullable=False),
    sa.Column('diet_restrictions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allergens', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('liked_foods_text', sa.String(), nullable=True),
    sa.Column('disliked_foods_text', sa.String(), nullable=True),
    sa.Column('liked_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('disliked_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('logged_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_event_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_event_id'], ['menu_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_event_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_event_id'], ['menu_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    op.drop_table('logged_meals')
    op.drop_table('user_preferences')
    op.drop_table('menu_events')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nutrition_matches_item_name'), table_name='nutrition_matches')
    op.drop_table('nutrition_matches')
    op.drop_table('eateries')
    op.drop_index(op.f('ix_diet_tags_item_name'), table_name='diet_tags')
    op.drop_table('diet_tags')
    # ### end Alembic commands ###
